# Generated by Django 5.0.4 on 2024-04-17 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
                ('descr', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='DriveAxelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
                ('descr', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель ведущего моста',
                'verbose_name_plural': 'Модели ведущих мостов',
            },
        ),
        migrations.CreateModel(
            name='EngineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
                ('descr', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель двигателя',
                'verbose_name_plural': 'Модели двигателей',
            },
        ),
        migrations.CreateModel(
            name='FailurePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
                ('descr', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Узел отказа',
                'verbose_name_plural': 'Узлы отказа',
            },
        ),
        migrations.CreateModel(
            name='GearType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
                ('descr', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель трансмиссии',
                'verbose_name_plural': 'Модели трасмиссий',
            },
        ),
        migrations.CreateModel(
            name='RepairMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
                ('descr', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Способ восстановления',
                'verbose_name_plural': 'Способы восстановления',
            },
        ),
        migrations.CreateModel(
            name='ServiceFirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
                ('descr', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Сервисная компания',
                'verbose_name_plural': 'Сервисные компании',
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
                ('descr', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Вид ТО',
                'verbose_name_plural': 'Виды ТО',
            },
        ),
        migrations.CreateModel(
            name='SteerAxelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
                ('descr', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель управляемого моста',
                'verbose_name_plural': 'Модели управляемых мостов',
            },
        ),
        migrations.CreateModel(
            name='TechType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
                ('descr', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель техники',
                'verbose_name_plural': 'Модели техники',
            },
        ),
        migrations.CreateModel(
            name='SilantPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CLIENT', 'Клиент'), ('SERVICE', 'Сервисная организация'), ('MANAGER', 'Менеджер')], max_length=16, verbose_name='Роль')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='silant.client', verbose_name='Клиент')),
                ('service_firm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='silant.servicefirm', verbose_name='Сервисная организация')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Право доступа',
                'verbose_name_plural': 'Права доступа',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=64, verbose_name='Зав. № машины')),
                ('engine_number', models.CharField(max_length=64, verbose_name='Зав. № двигателя')),
                ('gear_number', models.CharField(max_length=64, verbose_name='Зав. № трансмиссии')),
                ('drive_axel_number', models.CharField(max_length=64, verbose_name='Зав. № ведущего моста')),
                ('steer_axel_number', models.CharField(max_length=64, verbose_name='Зав. № управляемого моста')),
                ('contract', models.CharField(blank=True, max_length=64, null=True, verbose_name='Договор поставки, №, дата')),
                ('shipping_date', models.DateField(verbose_name='Дата отгрузки с завода')),
                ('consumer', models.CharField(max_length=64, verbose_name='Грузополучатель')),
                ('address', models.CharField(max_length=128, verbose_name='Адрес поставки')),
                ('equipment', models.TextField(blank=True, null=True, verbose_name='Комплектация (доп. опции)')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='silant.client', verbose_name='Клиент')),
                ('drive_axel_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='silant.driveaxeltype', verbose_name='Модель ведущего моста')),
                ('engine_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='silant.enginetype', verbose_name='Модель двигателя')),
                ('gear_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='silant.geartype', verbose_name='Модель трансмиссии')),
                ('service_firm', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='silant.servicefirm', verbose_name='Сервисная компания')),
                ('steer_axel_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='silant.steeraxeltype', verbose_name='Модель управляемого моста')),
                ('tech_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='silant.techtype', verbose_name='Модель техники')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата проведения ТО')),
                ('hours', models.PositiveIntegerField(verbose_name='Наработка, м/час')),
                ('order_number', models.CharField(max_length=64, verbose_name='№ заказа-наряда')),
                ('order_date', models.DateField(verbose_name='Дата заказа-наряда')),
                ('service_firm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='silant.servicefirm', verbose_name='Сервисная компания')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='silant.servicetype', verbose_name='Вид ТО')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='silant.vehicle', verbose_name='Машина')),
            ],
            options={
                'verbose_name': 'ТО',
                'verbose_name_plural': 'ТО',
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_date', models.DateField(verbose_name='Дата отказа')),
                ('hours', models.PositiveIntegerField(verbose_name='Наработка, м/час')),
                ('failure_type', models.TextField(verbose_name='Описание отказа')),
                ('spare', models.TextField(blank=True, null=True, verbose_name='Использованные запчасти')),
                ('repaired_date', models.DateField(verbose_name='Дата восстановления')),
                ('failure_part', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='silant.failurepart', verbose_name='Узел отказа')),
                ('repair_method', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='silant.repairmethod', verbose_name='Способ восстановления')),
                ('service_firm', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='silant.servicefirm', verbose_name='Сервисная компания')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='silant.vehicle', verbose_name='Машина')),
            ],
            options={
                'verbose_name': 'Рекламация',
                'verbose_name_plural': 'Рекламации',
            },
        ),
    ]
